# Generated by Django 4.2 on 2023-04-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_destination_destinationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=250)),
                ('pincode', models.IntegerField()),
                ('password', models.CharField(max_length=250)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
