# Generated by Django 4.2 on 2023-04-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_guide_pricing_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='thumbnail',
            field=models.ImageField(default=0, upload_to='destination'),
            preserve_default=False,
        ),
    ]
