# Generated by Django 4.2 on 2023-04-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_destination_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='languages_known',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
