# Generated by Django 4.2 on 2023-04-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_guide_languages_known'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='pricing',
            field=models.IntegerField(null=True),
        ),
    ]
