# Generated by Django 4.2 on 2023-04-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0008_alter_guide_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='image',
            field=models.ImageField(null=True, upload_to='guide'),
        ),
    ]
