# Generated by Django 4.2 on 2023-04-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0010_remove_request_time_remove_request_total_peoples'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='total_peoples',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
