# Generated by Django 4.2 on 2023-04-14 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0011_request_total_peoples'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
