# Generated by Django 4.2 on 2023-04-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0012_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='guide_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='guide_place',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
