# Generated by Django 4.2 on 2023-04-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0013_request_guide_name_request_guide_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='country',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='state',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
