# Generated by Django 4.2 on 2023-04-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0014_guide_country_guide_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='Requested', max_length=200),
        ),
    ]
