# Generated by Django 4.2 on 2023-04-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0015_request_price_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='pricing',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
