# Generated by Django 4.2 on 2023-04-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0017_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
