# Generated by Django 4.2 on 2023-04-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0018_request_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='price',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
