# Generated by Django 4.2 on 2023-04-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0024_alter_request_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
