# Generated by Django 4.2 on 2023-04-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0027_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Japan', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Tokyo', max_length=200),
        ),
    ]
