# Generated by Django 4.2 on 2023-04-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0028_order_country_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Paid', max_length=200),
        ),
    ]
