# Generated by Django 4.2 on 2023-05-04 05:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0031_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='destination'),
        ),
    ]
