# Generated by Django 4.2 on 2023-05-05 05:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0032_alter_destination_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='destination'),
        ),
    ]
