# Generated by Django 4.2 on 2023-05-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0033_alter_destination_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='is_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
