# Generated by Django 4.2 on 2023-05-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0036_userwallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
