# Generated by Django 4.2 on 2023-05-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0038_order_journey_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
