# Generated by Django 4.2 on 2023-05-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0039_alter_userwallet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='video',
            field=models.FileField(null=True, upload_to='guide'),
        ),
    ]
