# Generated by Django 4.2 on 2023-05-15 11:02

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0041_alter_guide_image_alter_guide_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', verbose_name='Video'),
        ),
    ]
