# Generated by Django 4.2 on 2023-05-16 09:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0042_alter_guide_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
