# Generated by Django 4.2 on 2023-05-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0044_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='is_blocked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
