# Generated by Django 4.2 on 2023-05-18 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0045_guide_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.guide')),
            ],
        ),
    ]
