# Generated by Django 4.2 on 2023-05-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0047_rename_user_id_guidewallet_guide_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guide_withdraw_status',
            field=models.BooleanField(default=False),
        ),
    ]
