# Generated by Django 4.2 on 2023-04-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=200)),
                ('pincode', models.BigIntegerField()),
                ('langages_known', models.CharField(max_length=200)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
