# Generated by Django 4.2 on 2023-04-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guideApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='langages_known',
            new_name='languages_known',
        ),
    ]
