# Generated by Django 4.2 on 2023-04-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideApp', '0002_rename_langages_known_guide_languages_known'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='is_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
