# Generated by Django 4.2 on 2023-04-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guideApp', '0003_guide_is_allowed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
