# Generated by Django 4.2 on 2023-05-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0048_order_guide_withdraw_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('guide_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userApp.guide')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userApp.user')),
            ],
        ),
    ]
